services:
  db:
    image: mariadb:10.11
    container_name: dolibarr_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dolibarr-db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  dolibarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dolibarr_web
    depends_on:
      - db
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_NAME: ${MYSQL_DATABASE}
      DOLI_DB_USER: ${MYSQL_USER}
      DOLI_DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DOLIBARR_PORT}:80"
    volumes:
      - dolibarr-data:/var/www/html/documents


volumes:
  dolibarr-db-data:
  dolibarr-data:
